addr2line -e build/buildroot/build/optee-os-custom/out/core/tee.elf 0xde01e3d4
addr2line -e build/buildroot/build/optee-os-custom/out/core/tee.elf 0xde04f779
addr2line -e build/buildroot/build/optee-os-custom/out/core/tee.elf 0xde01e3e3
addr2line -e build/buildroot/build/optee-os-custom/out/core/tee.elf 0xde01e5cf
addr2line -e build/buildroot/build/optee-os-custom/out/core/tee.elf 0xde01e91d
addr2line -e build/buildroot/build/optee-os-custom/out/core/tee.elf 0xde01ec93
addr2line -e build/buildroot/build/optee-os-custom/out/core/tee.elf 0xde022455
addr2line -e build/buildroot/build/optee-os-custom/out/core/tee.elf 0xde022525
addr2line -e build/buildroot/build/optee-os-custom/out/core/tee.elf 0xde022e39
addr2line -e build/buildroot/build/optee-os-custom/out/core/tee.elf 0xde025891
addr2line -e build/buildroot/build/optee-os-custom/out/core/tee.elf 0xde04cbd5
addr2line -e build/buildroot/build/optee-os-custom/out/core/tee.elf 0xde00419f
addr2line -e build/buildroot/build/optee-os-custom/out/core/tee.elf 0xde0001a0
