# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:trixie

    env:
      FORCE_UNSAFE_CONFIGURE: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          apt update
          apt install -y python3-invoke sudo git
          inv install

      - name: Build
        run: |
          inv build-bsp

          mkdir -p image
          mv build/buildroot/.config            image/config
          mv build/buildroot/images/sdcard.img  image/sdcard.img

      - name: Upload sdcard
        uses: actions/upload-artifact@v4
        with:
          name: bsp_seeed_studio_stm32mp135d_prod_image
          path: |
            image/config              
            image/sdcard.img
